<?php
/**
 * @file
 * blocks_views.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function blocks_views_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['views--exp-pictures_map-feed_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '-exp-pictures_map-feed_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'browse/pictures/map',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -28,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-1098a3e77f89ec86c72349ecded49ae1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '1098a3e77f89ec86c72349ecded49ae1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-249bcfebeb7cd4ac9adf6248c802a691'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '249bcfebeb7cd4ac9adf6248c802a691',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-2588ed9bc64b6686115eba5460025e79'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '2588ed9bc64b6686115eba5460025e79',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => 'dashboard_main',
        'status' => 1,
        'theme' => 'petal',
        'weight' => -25,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-44ef0468d3256ab275805ed35d3599fd'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '44ef0468d3256ab275805ed35d3599fd',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-635af42bf5fe9e60fa4c2afc31475fcb'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '635af42bf5fe9e60fa4c2afc31475fcb',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-654f89e3aab72bf17e13abf68ab8cc42'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '654f89e3aab72bf17e13abf68ab8cc42',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'observations*',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-73a7e487b9876f5e0e74dfcec31c936b'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '73a7e487b9876f5e0e74dfcec31c936b',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-890d731c11f548f12a8b03e269efe7b9'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '890d731c11f548f12a8b03e269efe7b9',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-a63079788b0d983bea5a09b9eaa5671b'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'a63079788b0d983bea5a09b9eaa5671b',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => 'dashboard_main',
        'status' => 1,
        'theme' => 'petal',
        'weight' => -23,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_branches-block_branch_admin'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_branches-block_branch_admin',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_listings-block_class'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_listings-block_class',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_listings-block_deprecated'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_listings-block_deprecated',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_listings-block_elements'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_listings-block_elements',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_listings-block_files'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_listings-block_files',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_listings-block_groups'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_listings-block_groups',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_listings-block_items_file'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_listings-block_items_file',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_listings-block_listing'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_listings-block_listing',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_listings-block_services'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_listings-block_services',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_members-block_member_list'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_members-block_member_list',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-api_projects-block_project_list'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_projects-block_project_list',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'api*',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -40,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-api_search-block_search_results'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'api_search-block_search_results',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-c01aecd6db65dfaa8c65e091f1d7faa9'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'c01aecd6db65dfaa8c65e091f1d7faa9',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-c3153e46cd0e282f9794b60e26b2de2b'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'c3153e46cd0e282f9794b60e26b2de2b',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-collection_observations-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'collection_observations-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'collections/*',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -23,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-dashboard_current_user-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'dashboard_current_user-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => 'dashboard_sidebar',
        'status' => 1,
        'theme' => 'petal',
        'weight' => -17,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-dashboard_summary_terms-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'dashboard_summary_terms-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => 'dashboard_main',
        'status' => 1,
        'theme' => 'petal',
        'weight' => -24,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-e3fe442c287db409b744e3397882a8f3'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'e3fe442c287db409b744e3397882a8f3',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-f609767c9f092016590274d325941640'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'f609767c9f092016590274d325941640',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-fed2ed5bb5357a0cb5d9b1a7192709ee'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'fed2ed5bb5357a0cb5d9b1a7192709ee',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-observations_of_taxon-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'observations_of_taxon-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'taxa/*',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -19,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-pictures_map-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'pictures_map-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'browse/pictures/map',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -25,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-summary_of_user_s_content-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'summary_of_user_s_content-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'my/contributions',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -30,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 7,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-taxon_observations_map-block_1'] = array(
    'cache' => -1,
    'css_class' => 'left',
    'custom' => 0,
    'delta' => 'taxon_observations_map-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'taxonomy/term/*',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => -25,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['views-user_content_summary-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'user_content_summary-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'users*',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'casabio',
        'weight' => 0,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-user_observations-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'user_observations-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'my/contributions',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -21,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-user_pictures-block_1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'user_pictures-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'my/contributions',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -20,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['views-user_s_collections-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'user_s_collections-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'my/contributions',
    'roles' => array(),
    'themes' => array(
      'casabio' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'casabio',
        'weight' => -22,
      ),
      'petal' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'petal',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  return $export;
}
