<?php
/**
 * @file
 * Description…
 */




// =============================================================================
/* CONTENTS

  [NU] = Function is not currently used

  // Generic module hook functions
  [NU] contribute_help()
  contribute_menu()
  contribute_init()

  // Menu callbacks
  contribute_observation_page()

  pass_collection_info_to_js()

  // Block functions
  contribute_block_info()
  contribute_block_view()
  steps_block_view()

  create_nav_button()
  get_contribute_mo_finish_content()

  contribute_locality_page_callback()
  is_page()
*/





// =============================================================================
/**
 * Implements hook_help().
 */
// function contribute_help($path, $arg) {}





// =============================================================================
/**
 * Implements hook_menu().
 */
function contribute_menu() {

  $items['contribute/upload'] = array(
    'title'             => 'Contribute Multiple Observations', // Because this is the first step, this needs to be clear. The steps block shows it's the upload page.
    'page callback'     => 'get_upload_form_content',
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    'type'              => MENU_NORMAL_ITEM,
    // 'menu_name'         => 'menu-contribute',
  );

  // Last step of the Contribute MO process.
  $items['contribute/finished/%'] = array(
    'title'             => 'Contribution Complete',
    'page callback'     => 'get_contribute_mo_finish_content',
    'page arguments'    => array(2),
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    'type'              => MENU_NORMAL_ITEM,
  );

  $items['contribute/observation'] = array(
    'title'             => 'Contribute Observation',
    'page callback'     => 'contribute_observation_page',
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    'type'              => MENU_NORMAL_ITEM,
    // 'menu_name'         => 'menu-contribute',
  );

  // Now a webform.
  // $items['contribute/request'] = array();

  // Catch-all page for contributions that don't show in the Contribute menu.
  $items['contribute/other'] = array(
    'title'             => 'Contribute to CasaBio',
    'page callback'     => 'contribute_other_page_callback',
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    'type'              => MENU_NORMAL_ITEM,
    'menu_name'         => 'menu-contribute',
  );

  $items['contribute/habitat'] = array(
    'title'             => 'Contribute Habitat',
    'page callback'     => 'contribute_habitat_page_callback',
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    'type'              => MENU_NORMAL_ITEM,
  );

  $items['contribute/locality'] = array(
    'title'             => 'Add a Locality',
    'page callback'     => 'contribute_locality_page_callback',
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    'type'              => MENU_NORMAL_ITEM,
  );

  $items['contribute/taxon'] = array(
    'title'             => 'Add a Taxon',
    'page callback'     => 'contribute_taxon_page_callback',
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    'type'              => MENU_NORMAL_ITEM,
  );

  $items['contribute/taxon/etymology/%'] = array(
    'title'             => 'Contribute Etymology',
    'page callback'     => 'contribute_taxon_etymology_page_callback',
    'page arguments'    => array(3),
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    'type'              => MENU_NORMAL_ITEM,
  );

  return $items;
}




function user_has_roles($roles) {
  if (user_is_logged_in()) {
    global $user;
    // If administrator, always return true.
    if (in_array('administrator', $user->roles)) {
      return TRUE;
    }
    // For each role provided, check if user has it.
    foreach ($roles as $role) {
      if (in_array($role, $user->roles)) {
        return TRUE;
      }
    }
  }
  else {
    return FALSE;
  }
}






/**
 * Implements hook_init().
 */
function contribute_init() {

  $js_files = array();
  $css_files = array();

  // Add a JS setting variable: current_page

  $known_pages = array('upload', 'group', 'picture_info', 'observation_info');

  // Pass current page as '' to js in case it is not known.
  drupal_add_js(array('contribute' => array('current_page' => '')), 'setting');

  // If current page is known, pass its name to js.
  foreach ($known_pages as $page_name) {
    if (is_page($page_name)) {
      // dpm($page_name, 'is $page_name');
      drupal_add_js(array('contribute' =>
        array('current_page' => $page_name)), 'setting');
    }
  }


  // All Contribute pages
  if (drupal_match_path(current_path(), 'contribute*')) {
    $js_files += array(
      drupal_get_path('module', 'contribute') . '/scripts/contribute.js',
    );
    $css_files += array(
      libraries_get_path('lightbox') . '/dist/css/lightbox.css',
    );

    $js_files_footer = libraries_get_path('lightbox') . '/dist/js/lightbox.js';
    drupal_add_js($js_files_footer, array('scope' => 'footer'));
  }

  // Upload page
  if (drupal_match_path(current_path(), 'contribute/upload')) {
    $js_files += array(
      drupal_get_path('module', 'contribute') . '/scripts/contribute_maps.js',
    );
  }

  // Edit Selected pages
  // The paths for which the files should be included
  $pages_with_maps_paths = array(
    'contribute/multiple-observations/observation-info*',
    'contribute/multiple-observations/habitats*',
  );
  foreach ($pages_with_maps_paths as $active_path) {
    if (drupal_match_path(current_path(), $active_path)) {

      // dpm('Is Edit Observation Information page');

      pass_collection_info_to_js();

      // Add a JS setting variable: current_page
      drupal_add_js(array('contribute' =>
        array('current_path' => $active_path)), 'setting');

      $js_files += array(
        libraries_get_path('openlayers3') . '/build/ol-debug.js',
        drupal_get_path('module', 'contribute') . '/scripts/contribute_maps.js',
      );
      // dpm($js_files, 'js_files');
    }
  }

  // Contribute observation page
  if (drupal_match_path(current_path(), 'contribute/observation')) {
    $js_files += array(
      libraries_get_path('openlayers3') . '/build/ol-debug.js',
      drupal_get_path('module', 'contribute') . '/scripts/contribute_maps.js',
    );
  }

  // dpm($js_files, '$js_files');
  foreach ($js_files as $path) {
    drupal_add_js($path);
  }
  foreach ($css_files as $path) {
    drupal_add_css($path);
  }
}





// =======================================================================================
/**
 * Implements hook_permission().
 */
function contribute_permission() {
  return array(
    'can contribute content' => array(
      'title' => t('Can contribute content'),
      'description' => t('Can create and edit own content of standard types'),
    ),
  );
}





// =======================================================================================
/**
 * Callback for contribute/observation page that displays its content.
 */
function contribute_other_page_callback() {

  $content = array(
    '#markup' =>
        '<p>' . l('Contribute a Habitat', 'contribute/habitat')
      . ' &nbsp;&nbsp;(learn about ' . l('habitats', 'help') . ')</p>'

      . '<p>' . l('Contribute a Locality', 'contribute/locality')
      . ' &nbsp;&nbsp;(learn about ' . l('localities', 'help') . ')</p>'

      . '<p>' . l('Contribute an Observation', 'contribute/observation')
      . ' &nbsp;&nbsp;(learn about ' . l('observations', 'help') . ')</p>'

      . '<p>' . '<del>Contribute a CREW Species Observation</del>' . '</p>'

      . '<p><em>Collections</em> and <em>Pictures</em> can only be added '
      . 'in the Contribute Observations process.</p>'

      . '<p><em>Identifictions</em> and <em>Interactions</em> cannot be added on their own;'
      . ' they must be added to an observation.</p>'

      . '<p><em>Taxa</em>  can only be added by maintainers.</p>'
    ,
  );

  return $content;
}





// =======================================================================================
/**
 * Callback for contribute/observation page that displays its content.
 */
function contribute_observation_page() {

  $content = "";

  $entity_type = 'node';
  $entity_bundle_key =  'type';
  $bundle = 'observation';

  $node = entity_create($entity_type, array(
    $entity_bundle_key => $bundle,
  ));

  module_load_include('inc', 'node', 'node.pages');
  $content = drupal_get_form($bundle . '_node_form', $node, ['form_view_mode' => 'contribute_new']);

  return $content;
}




/*
 * Adds the collection's location information to the JS settings.
 */
function pass_collection_info_to_js() {
  // dpm('pass_collection_info_to_js');

  // Gets the collection's nid from the current path.

  $nid;

  $paths = array(
    'contribute/multiple-observations/picture-info*',
    'contribute/multiple-observations/observation-info*',
    'contribute/multiple-observations/habitats*',
  );

  $matching_path;

  // Determine if the current path is one of the targeted paths.
  for ($i = 0; $i < sizeof($paths); $i++) {
    if (drupal_match_path(current_path(), $paths[$i])) {
      $matching_path = $i;
    }
  }

  // If no targeted path was matched
  if (! isset($matching_path)) return;

  $path_wild_pos = strpos($paths[$matching_path], '*');
  $nid = substr(current_path(), $path_wild_pos + 1);
  // dpm($nid, 'nid');

  if(isset($nid)) {

    // Loads the collection node and wraps it in a metadata wrapper.

    $collection_raw = node_load($nid);
    $collection = entity_metadata_wrapper('node', $collection_raw);

    if (isset($collection->field_location)) {
      $location = $collection->field_location->value();

      $collection_location = json_encode($location);
      $module_js_settings = array(
        'collection_location' => $collection_location,);
      drupal_add_js(array('edit_selected' => $module_js_settings), 'setting');
    }
  }
}





// =============================================================================
/**
 * Implements hook_block_info().
 */
function contribute_block_info() {
  $blocks = array();

  $blocks['steps'] = array(
    'info' => t('Contribute stages'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    // 'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}





// =============================================================================
/**
 * Implements hook_block_view().
 */
function contribute_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'steps' :
      $block['subject'] = t('Steps');
      $block['content'] = steps_block_view();
      break;
  }

  return $block;
}





// =============================================================================
/**
 * Implements hook_block_view().
 */
function steps_block_view() {

  // 'location_path' is the page that link is displayed on
  // 'destination_path' is the link's href value
  // 'content' is the text between the link's opening and closing tags
  // 'suffix' of a path is the string of characters after a wildcard ‘*’

  // Define the link info
  $links = array(
    // The Upload page is a form that has its own submit button
    // array(
    //   'location_path' => 'contribute/upload*',
    //   'destination_path' => base_path() . 'contribute/multiple-observations/picture-info',
    //   'content' => 'Save & Continue »',
    //   'keep_suffix' => TRUE,
    //   'classes' => ''),
    array(
      'location_path' => 'contribute/upload',
      'link_content' => '<span class="icon-file_upload"></span> 1. Upload pictures',
      'keep_suffix' => TRUE,
      'step_classes' => '',),
    array(
      'location_path' => 'contribute/multiple-observations/group*',
      'link_content' => '2. Group',
      'keep_suffix' => TRUE,
      'step_classes' => '',),
    array(
      'location_path' => 'contribute/multiple-observations/observation-info*',
      'link_content' => '3. Observation info',
      'keep_suffix' => TRUE,
      'step_classes' => '',),
    // array(
    //   'location_path' => 'contribute/multiple-observations/picture-info*',
    //   'link_content' => 'Picture info',
    //   'keep_suffix' => TRUE,
    //   'step_classes' => '',),
    // array(
    //   'location_path' => 'contribute/multiple-observations/habitats*',
    //   'link_content' => '<span class="icon-terrain"></span> Habitats',
    //   'keep_suffix' => FALSE,
    //   'step_classes' => '',),
  );

  $content = '';

  $content .= create_nav_button($links, 'prev');

  // Steps

  // If the current path matches a step's active path, make that step active
  foreach ($links as $key => $step_info) {
    if (drupal_match_path(current_path(), $step_info['location_path'])) {
      $links[$key]['step_classes'] = 'active';
    }
  }

  $content .= '<ul class="steps not-links">';

  // Add each step to the content as a list item
  foreach ($links as $key => $step_info) {
    $content .= '<li class="' . $step_info['step_classes'] . '">' . $step_info['link_content'] . '</li>';
  }

  $content .= '</ul>';

  $content .= create_nav_button($links, 'next');

  // dpm($content, 'content');
  return $content;
}





// =============================================================================
/**
 * Creates the markup for a button used beside the Contribute steps indicator.
 * Can create Previous or Next buttons.
 *
 * @param $links
 *   An array of link information arrays. Each item should be an array in the form:
 *   array(location_path, link_content, keep_suffix, step_classes)
 * @param $direction
 *   'prev' or 'next'.
 */
function create_nav_button($links, $direction) {

  $buttons;
  $link_content = '';
  $attributes = array(
    'class' => 'button',
  );
  $query = [];

  if ($direction == 'prev' || $direction == 'next') {
    $attributes['class'] .= ' raised';
  }
  if ($direction == 'prev') {
    $increment = -1;
    $link_content = '« Previous';
    $attributes['rel'] = 'prev';
    $attributes['class'] .= ' pointing-left';
  }
  elseif ($direction == 'next') {
    $increment = 1;
    $link_content = 'Continue »';
    $attributes['rel'] = 'next';
    $attributes['class'] .= ' pointing-right';
  }

  // dpm($links, '$links');
  for ($i = 0; $i < sizeof($links); $i++) {
    if (drupal_match_path(current_path(), $links[$i]['location_path'])) {
      // Suffix is the wildcard in the path, used as a contextual filter for views
      $suffix = '';
      $path = '';

      $path_wild_pos = strpos($links[$i]['location_path'], '*');
      $suffix = substr(current_path(), $path_wild_pos);
      $suffix = str_replace('/', '', $suffix); // Remove leading '/'.
      // dpm($suffix, '$suffix');

      // If current step is 'upload', and if this is the previous button
      if ($i == 0 && $direction == 'prev') {
        return '';
      }
      if ($i == 0 && $direction == 'next') {
        $attributes['disabled'] = 'true';
        $suffix = '';
      }
      // If current step is 'group', and if this is the previous button (Can't go to first)
      if ($i == 1 && $direction == 'prev') {
        // return '<a class="' . $attributes['class'] . '" disabled>' . $link_content . '</a>';
        $path = str_replace("*", "", $links[$i + $increment]['location_path']);
        $query['collection'] = $suffix;
      }
      // If current step is 'observation info' and this is the next button (Finish)
      elseif ($i == sizeof($links) - 1 && $direction == 'next') {
        $link_content = 'Finish »';

        $path = 'contribute/finished/' . $suffix;
      }
      else {
        $path = str_replace("*", "", $links[$i + $increment]['location_path']) . '/' . $suffix;
      }
      // dpm($suffix, 'suffix');

      // $buttons = '<a class="button" href="' . $url . '">' . $links[$i]['content'] . '</a>';
      $buttons = l($link_content, $path, array(
        'attributes' => $attributes,
        'query' => $query,
      ));
      // @todo use Drupal's native l() instead.
    }
  }

  return $buttons;
}



// =============================================================================
/**
 * Page callback that concludes the 'Contribute Multiple Observations' process.
 */
function get_contribute_mo_finish_content($collection_nid) {

  drupal_set_title('Collection ' . drupal_get_title());

  $nu_pictures = get_referencings_count('field_collection', $collection_nid, 'picture');
  $nu_observations = get_referencings_count('field_collection', $collection_nid, 'observation');

  $content =
    '<p>You uploaded <strong>' . $nu_pictures . '</strong> pictures.<br>'
    . 'You grouped the pictures into <strong>' . $nu_observations . '</strong> observations.<br>'

    . '<p><em>Thank you for contributing to CasaBio! We appreciate it.</em></p>'

    . '<h2>What next?</h2>'
    . '<ul>'
    . '<li>' . l("Contribute habitats", 'contribute/habitats/'
      . $collection_nid) . '</li>'
    . '<li>' . l("View the collection", 'node/' . $collection_nid) . '</li>'
    . '<li>' . l("Browse others’ contributions", 'browse') . '</li>'
    . '</ul>'
  ;
  return $content;
}



function contribute_locality_page_callback() {
  $vocabulary = taxonomy_vocabulary_machine_name_load('locality');

  if (! $vocabulary) {
    return '';
  }

  module_load_include('inc', 'taxonomy', 'taxonomy.admin');
  $edit = array();
  $taxonomy_form = drupal_get_form('taxonomy_form_term', $edit, $vocabulary, ['form_view_mode' => 'contribute']);

  return drupal_render($taxonomy_form);
}



function contribute_taxon_page_callback() {
  $vocabulary = taxonomy_vocabulary_machine_name_load('taxa');

  if (! $vocabulary) {
    return '';
  }

  module_load_include('inc', 'taxonomy', 'taxonomy.admin');
  $edit = array();
  $taxonomy_form = drupal_get_form('taxonomy_form_term', $edit, $vocabulary, ['form_view_mode' => 'contribute']);

  return drupal_render($taxonomy_form);
}





/**
 * Determines if the current page is the specified page.
 * 
 * @param string $name
 *   Internal name of page, such as 'picture_info'.
 */
function is_page($name) {
  $casa_paths = array(
    'upload' =>           'contribute/upload',
    'group' =>            'contribute/multiple-observations/group*',
    'picture_info' =>     'contribute/multiple-observations/picture-info*',
    'observation_info' => 'contribute/multiple-observations/observation-info*',
  );

  // If any contribute page
  if ($name == 'contribute*') {
    // Can be extended to match Contribute pages that don't start with 'contribute/'
    return drupal_match_path(current_path(), 'contribute*');
  }
  else {
    return drupal_match_path(current_path(), $casa_paths[$name]);
  }
}