<?php
/**
 * @file
 * Description…
 */




// =============================================================================
/* CONTENTS

  [NU] = Function is not currently used

  // Generic module hook functions
  [NU] edit_selected_help()
  edit_selected_menu()
  edit_selected_init()

  number_specimens_callback()

  // Block functions
  edit_selected_block_info()
  edit_selected_block_view()

  edit_selected_buttons_block_content()
  array_replace_recursive_search()
  is_page()
*/





// =============================================================================
/**
 * Implements hook_help().
 * Inline Entity Form
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
// function edit_selected_help($path, $arg) {}





// =============================================================================
/**
 * Implements hook_menu().
 */
function edit_selected_menu() {
  $items['ajax/number_specimens'] = array(
    // 'title'             => 'Number Specimens',
    'page callback'     => 'number_specimens_callback',
    // 'page arguments'    => array('casa_upload_upload_form'),
    'access callback'   => TRUE,
    // 'access arguments'  => array('bulk upload media'),
    // 'file'              => 'casa_upload.upload.inc',
    'type'              => MENU_CALLBACK,
  );

  $items['ajax/identifications/by_collection/%'] = array(
    'page callback'     => 'identifications_by_collection',
    'page arguments'    => array(3),
    'access callback'   => TRUE,
    // 'access arguments'  => array('bulk upload media'),
    // 'file'              => 'casa_upload.upload.inc',
    'delivery callback' => 'ajax_deliver',
    'type'              => MENU_CALLBACK,
  );

  $items['ajax/interactions/by_collection/%'] = array(
    'page callback'     => 'interactions_by_collection',
    'page arguments'    => array(3),
    'access callback'   => TRUE,
    // 'access arguments'  => array('bulk upload media'),
    // 'file'              => 'casa_upload.upload.inc',
    'delivery callback' => 'ajax_deliver',
    'type'              => MENU_CALLBACK,
  );

  $items['contribute/multiple-observations/observation-info/%'] = array(
    // 'title'             => 'Observation Information',
    'page callback'     => 'contribute_mo_observation_page',
    'page arguments'    => array(3),
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    // 'file'              => 'casa_upload.upload.inc',
    'type'              => MENU_NORMAL_ITEM,
  );

  $items['contribute/multiple-observations/picture-info/%'] = array(
    // 'title'             => 'Observation Information',
    'page callback'     => 'contribute_mo_picture_page',
    'page arguments'    => array(3),
    'access callback'   => 'user_access',
    'access arguments'  => array('can contribute content'),
    // 'file'              => 'casa_upload.upload.inc',
    'type'              => MENU_NORMAL_ITEM,
  );

  return $items;
}





/**
 * Implements hook_init(). Primarily includes needed libraries and files.
 */
function edit_selected_init() {

  if (is_page('picture_info')
    || is_page('observation_info')
    || is_page('upload')) {

    // Include required JavaScript files and libraries
    $js_files = array(
      // libraries_get_path('openlayers3') . '/build/ol-debug.js',
      libraries_get_path('jquery.hotkeys') . '/jquery.hotkeys.js',
      drupal_get_path('module', 'selection') . '/scripts/selection.js',
      drupal_get_path('module', 'edit_selected') . '/scripts/edit_selected.js',
      drupal_get_path('module', 'edit_selected') . '/scripts/form_prefiller.js',
      drupal_get_path('module', 'edit_selected') . '/scripts/es_api_interactions.js',
      // drupal_get_path('module', 'edit_selected') . '/scripts/es_maps.js',
    );

    foreach ($js_files as $path) {
      drupal_add_js($path);
    }

    // Add requirements for ctools’ modal (dialog).
    ctools_include('modal');
    ctools_modal_add_js();

    drupal_add_library('system', 'drupal.collapse');

    // Add a JS setting variable: current_page

    $known_pages = array('upload', 'picture_info', 'observation_info');

    foreach ($known_pages as $page_name) {
      if (is_page($page_name)) {
        drupal_add_js(array('edit_selected' =>
          array('current_page' => $page_name)), 'setting');
      }
    }

    // if (is_page('picture_info')) {
    //   drupal_add_js(array('edit_selected' =>
    //     array('current_page' => 'picture_info')), 'setting');
    // }
    // elseif (is_page('observation_info')) {
    //   drupal_add_js(array('edit_selected' =>
    //     array('current_page' => 'observation_info')), 'setting');
    // }

  }
}

// function edit_selected_js_alter(&$javascript) {
//   dpm($javascript, '$javascript');
//   // if ($some_condition) {
//   //   unset($javascript['path/to/script.js']);
//   // }
// }





function number_specimens_callback() {
  $post = $_POST;
  // dpm($post, 'post');

  $nids = $post['nids'];
  $method = $post['method'];
  $starting_number = $post['starting-number'];

  number_specimens($nids, $method, $starting_number);
}



/**
 * Sets an incremental value for Specimen ID field for observations.
 *
 * @param string $method
 *   Either 'increment' or 'append'.
 */
function number_specimens($nids, $method, $starting_number) {
  // dpm($nids, '$nids');
  // dpm($method, '$method');
  // dpm($starting_number, '$starting_number');

  // @todo Validate form values

  $nids = explode(',', $nids);
  // dpm($nids, '$nids');
  $nodes;
  foreach ($nids as $nid) {
    $node_raw = node_load($nid);
    if ($node_raw) {
      $nodes[] = entity_metadata_wrapper('node', $node_raw);
    }
  }
  // dpm($nodes, '$nodes');

  $method = $method;
  $starting_sid = $starting_number;

  for ($i = 0; $i < count($nodes); $i++) {
    $sid;

    if($method == 'increment') {
      $sid = $starting_sid + $i;
    }
    elseif ($method == 'append') {
      $sid = $starting_sid . '-' . $i;
    }

    $nodes[$i]->field_specimen_id->set($sid);
    $nodes[$i]->save();
  }

  // return "This is just a callback endpoint (URL).";
}



/**
 * Provides an array of all identifications that reference an observation
 * within the specified collection (that reference it).
 */
function identifications_by_collection($collection_nid) {
  $observations = get_observations_referencing_collection($collection_nid);
  // dpm($observations, '$observations');
  $identifications = [];

  foreach ($observations as $nid => $observation) {
    $handler = restful()
      ->getResourceManager()
      ->getPlugin('identifications:0.1');

    $query['filter'] = array('observation' => $nid);

    $get_result = restful()
      ->getFormatterManager()
      ->format($handler->doGet('', $query));
    // dpm(json_decode($get_result), '$get_result');

    $identifications = array_merge($identifications,
      json_decode($get_result)->data);
  }
  // dpm($identifications, '$identifications');

  $result = array('data' => $identifications);
  $response = array('#type' => 'ajax', '#commands' => $result);
  return $response;
}



/**
 * Provides an array of all identifications that reference an observation
 * within the specified collection (that reference it).
 */
function interactions_by_collection($collection_nid) {
  $observations = get_observations_referencing_collection($collection_nid);
  // dpm($observations, '$observations');
  $interactions = [];

  foreach ($observations as $nid => $observation) {
    $handler = restful()
      ->getResourceManager()
      ->getPlugin('interactions:0.1');

    $query['filter'] = array('observation' => $nid);

    $get_result = restful()
      ->getFormatterManager()
      ->format($handler->doGet('', $query));
    // dpm(json_decode($get_result), '$get_result');

    $interactions = array_merge($interactions,
      json_decode($get_result)->data);
  }
  // dpm($interactions, '$interactions');

  $result = array('data' => $interactions);
  $response = array('#type' => 'ajax', '#commands' => $result);
  return $response;
}




function contribute_mo_observation_page($collection_nid) {
  // dpm($collection_nid, '$collection_nid');

  $content = array();

  // Add the secondary toolbar
  $file_url = drupal_get_path('module', 'edit_selected') . '/markup/observations_toolbar_secondary.html';
  $content['toolbar'] = array(
    '#markup' => file_get_contents($file_url),
  );

  // Add the view
  $name = 'contribute_observations_info'; // @todo rename this
  $display_id = 'block_1';
  $content['view'] = array(
    '#markup' => views_embed_view($name, $display_id, $collection_nid),
  );


  // Add the edit form
  $block_content = get_edit_selected_form('observation');
  // dpm($block_content, '$block_content');

  $content['edit_block'] = array(
    '#type' => 'fieldset',
    $block_content,
    '#attributes' => array(
      'class' => array('edit_form_wrapper'),
    ),
  );

  // Add the identification form (with embedded view)
  $id_form_content = get_identify_selected_form();
  $content['identify_block'] = array(
    '#type' => 'fieldset',
    $id_form_content,
    '#attributes' => array(
      'class' => array('identify_form_wrapper'),
    ),
  );

  // Add the interaction form
  $content['add_interaction'] = array(
    '#type' => 'fieldset',
    get_interaction_form(),
    '#attributes' => array(
      'class' => array('interaction_form_wrapper'),
    ),
  );

  // dpm($content, '$content');
  return $content;
}



function get_interaction_form() {
  $content = array();

  // Embed the species view

  $content['identified_species'] = array(
    '#type' => 'fieldset',
    '#title' => t('Choose a species'),
    '#weight' => 0,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    '#attributes' => array(
      'class' => array('collapsible', 'collapsed'),
    ),
    '#attached' => array(
      'library' => array(
        array('system', 'drupal.collapse'),
      ),
    ),
  );

  $view_name = 'species_reference_selector_widget';
  $display_id = 'entityreference_view_widget_2'; // 'default'

  $view_rendered = views_embed_view($view_name, $display_id);

  $content['identified_species']['chooser'] = array(
    '#type' => 'markup',
    '#markup' => $view_rendered,
  );


  // Embed an identification form

  global $user;
  $values = array(
    'type' => 'identification',
    'uid' => $user->uid,
    'status' => 1,
  );
  $node = entity_create('node', $values);

  $form = drupal_get_form('node_form', $node, ['form_view_mode' => 'contribute_new']);
  // dpm($form, '$form');
  $form['actions']['#access'] = FALSE;
  $form['field_identified_species']['#access'] = FALSE;

  $content['identification_form'] = array(
    $form,
    '#weight' => 1,
  );


  // Embed the interaction form

  global $user;
  $values = array(
    'type' => 'interaction',
    'uid' => $user->uid,
    'status' => 1,
  );
  $node = entity_create('node', $values);

  $content['interaction_form'] = array(
    drupal_get_form('node_form', $node, ['form_view_mode' => 'add_to_observation']),
    '#weight' => 2,
  );
  return $content;
}




function contribute_mo_picture_page($collection_nid) {
  // dpm($collection_nid, '$collection_nid');

  $content = array();

  // Add the secondary toolbar
  $file_url = drupal_get_path('module', 'edit_selected') . '/markup/pictures_toolbar_secondary.html';
  $content['toolbar'] = array(
    '#markup' => file_get_contents($file_url),
  );

  // Add the view
  $name = 'contribute_pictures_info'; // @todo rename this
  $display_id = 'block_1';
  $content['view'] = array(
    '#markup' => views_embed_view($name, $display_id, $collection_nid)
  );

  // Add the edit form
  $delta = 'edit_selected_pictures';

  $block_content = get_edit_selected_form('picture');
  // dpm($block_content, '$block_content');
  $content['edit_block'] = array(
    '#type' => 'fieldset',
    $block_content,
    '#attributes' => array(
      'class' => array('edit_form_wrapper'),
    ),
  );

  // dpm($content, '$content');
  return $content;
}





// =============================================================================
/**
 * Implements hook_block_info().
 */
function edit_selected_block_info() {
  $blocks = array();

  $blocks['edit_selected_buttons'] = array(
    'info' => t('Edit selection actions'),
    'cache' => DRUPAL_NO_CACHE, // Because the content depends on the page
  );

  // dpm($blocks, 'blocks');
  return $blocks;
}





// =============================================================================
/**
 * Implements hook_block_view().
 */
function edit_selected_block_view($delta = '') {
  // dpm($delta, 'delta');
  $block = array();

  switch ($delta) {
    // For the Selected Buttons block
    case 'edit_selected_buttons':
      $block['subject'] = t('Group Selected Buttons');
      $block['content'] = edit_selected_buttons_block_content();
      break;
  }

  return $block;
}





// =============================================================================
/**
 * Implements hook_block_view().
 */
function edit_selected_buttons_block_content() {
  $content = '<form id="selected_buttons">'
    // . '<button type="button" id="unselect" name="unselect" disabled>Unselect</button>'
    . '<button data-display=".edit_form_wrapper" id="edit"><span style="text-decoration: underline;">E</span>dit</button>';

  // If this is the '/picture-info' page
  if (is_page('picture_info')
    || is_page('upload')) {
    $file_url = drupal_get_path('module', 'edit_selected') . '/markup/pictures_toolbar_primary.html';
    $content .= file_get_contents($file_url);
  }
  // If this is the '/observation-info' page
  elseif (is_page('observation_info')) {
    $file_url = drupal_get_path('module', 'edit_selected') . '/markup/observations_toolbar_primary.html';
    $content .= file_get_contents($file_url);
  }

  $content .= '</form>';

  return $content;
}





include_once 'edit_selected_block.inc';
// require_once DRUPAL_ROOT . '/' .
//   variable_get('group_selected_block.inc', 'includes/group_selected_block.inc');





/**
 * Replaces the values of array1 with values having the same keys in the following array.
 * Does this recursively, traversing into each array and doing the same replacement.
 * Unlike array_replace(), this function does not add any new elements to array1.
 */
function array_replace_recursive_search(array $array1, array $array2) {
  foreach ($array1 as $key => $value) {
    // If $array1 has a key matching a key in $array2, replace its value with the corresping value from $array2
    foreach ($array2 as $a2key => $a2value) {
      if ($key === $a2key) {
        // dpm($array1);
        // dpm($value);
        if (is_array($value)) {
          $array1[$key] = [];
          $value = [];
        }
        else {
          $array1[$key] = $a2value;
          $value = $a2value;
        }
      }
    }
    $ignored_keys = array('changed', 'form_token');

    // For arrays, recurse
    if (is_array($value) && !in_array($key, $ignored_keys, TRUE)) {
      $array1[$key] = array_replace_recursive_search($value, $array2);
    }
  }
  return $array1;
}





// =============================================================================
/**
 * Determines if the current page is the specified page.
 */
function is_page($name) {
  $casa_paths = array(
    'upload' => 'contribute/upload',
    'picture_info' => 'contribute/multiple-observations/picture-info*',
    'observation_info' => 'contribute/multiple-observations/observation-info*',
  );

  return drupal_match_path(current_path(), $casa_paths[$name]);
}
