<?php
/**
 * @file
 * content_type_collection.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function content_type_collection_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_collector'.
  $field_bases['field_collector'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_collector',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_count_observations'.
  $field_bases['field_count_observations'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_count_observations',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'entityreference_count',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'entityreference_count',
  );

  // Exported field_base: 'field_count_pictures'.
  $field_bases['field_count_pictures'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_count_pictures',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'entityreference_count',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'entityreference_count',
  );

  // Exported field_base: 'field_date_collected'.
  $field_bases['field_date_collected'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_date_collected',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'date',
    'settings' => array(
      'cache_count' => 4,
      'cache_enabled' => 0,
      'granularity' => array(
        'day' => 'day',
        'hour' => 0,
        'minute' => 0,
        'month' => 'month',
        'second' => 0,
        'year' => 'year',
      ),
      'timezone_db' => '',
      'todate' => '',
      'tz_handling' => 'none',
    ),
    'translatable' => 0,
    'type' => 'datetime',
  );

  // Exported field_base: 'field_featured_pictures'.
  $field_bases['field_featured_pictures'] = array(
    'active' => 1,
    'cardinality' => 5,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_featured_pictures',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'picture' => 'picture',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
