<?php
/**
 * @file
 * Description…
 */





// =======================================================================================
/**
 * Implements hook_help().
 */
// function casa_services_help($path, $arg) {}





// =======================================================================================
/**
 * Implements hook_services_resources().
 */
function casa_services_services_resources() {

  $resources = array(
    // '#api_version' => 11,
  );

  $resources = array(
    'user' => array(
      'actions' => array(
        'current_user' => array(
          'help' => 'Get the current user; if logged in.',
          'callback' => '_user_resource_current_user',
          'file' => array('type' => 'module', 'module' => 'casa_services', 'name' => 'resources/casa_services'),
          'access callback' => '_user_resource_access',
          'access arguments' => array('view', $GLOBALS['user']->uid),
          'access arguments append' => FALSE,
          'args' => array(),
        ),
      ),
    ),
  );

  module_load_include('inc', 'casa_services', 'resources/observations_resource');
  module_load_include('inc', 'casa_services', 'resources/pictures_resource');
  module_load_include('inc', 'casa_services', 'resources/other_node_resources');
  module_load_include('inc', 'casa_services', 'resources/taxa_resource');

  $resources += _observations_resource_definition();
  $resources += _pictures_resource_definition();
  $resources += _other_node_resources_definition();
  $resources += _taxa_resource_definition();

  return $resources;
}



/**
 * @return boolean
 *   TRUE if the user is permitted access, FALSE otherwise.
 */
function _casa_node_resource_access($op = 'view', $args = array()) {
  // dpm($op, 'op');
  // dpm($args, 'args');

  if ($op == 'update') {
    $nids = explode('|', $args[0]);
    // dpm($nids, 'nids');
    if (count($nids) == 1) {
      return _node_resource_access($op, $args);
    }
    else {
      // // Adds backwards compatability with regression fixed in #1083242
      // if (isset($args[0])) {
      //   $args[0] = _services_access_value($args[0], 'node');
      // }

      // // Make sure we have an object or this all fails, some servers can
      // // mess up the types.
      // if (is_array($args[0])) {
      //   $args[0] = (object) $args[0];
      // }
      // elseif (!is_array($args[0]) && !is_object($args[0])) { //This is to determine if it is just a string happens on node/%NID
      //   $args[0] = (object) array('nid' => $args[0]);
      // }

      // if ($op != 'create' && !empty($args)) {
      //   $node = node_load($args[0]->nid);
      // }
      // elseif ($op == 'create') {
      //   if (isset($args[0]->type)) {
      //     $node = $args[0]->type;
      //     return node_access($op, $node);
      //   }
      //   else {
      //     return services_error(t('Node type is required'), 406);
      //   }
      // }
      // if (isset($node->nid) && $node->nid) {
      //   return node_access($op, $node);
      // }
      // else {
      //   return services_error(t('Node @nid could not be found', array('@nid' => $args[0]->nid)), 404);
      // }
      return TRUE;
    }
  }
  else {
    return _node_resource_access($op, $args);
  }
}





// =======================================================================================
/**
 * Implements hook_services_resources_alter().
 */
function casa_services_services_resources_alter(&$resources, &$endpoint) {
  // dpm($resources, 'resources');
  // dpm($endpoint, 'endpoint');
}





// =======================================================================================
/**
 * Implements hook_menu_alter().
 */
function casa_services_menu_alter(&$items) {
  // dpm($items, '$items');
}



/**
 * Implements hook_ctools_plugin_api().
 */
function casa_services_ctools_plugin_api($owner, $api) {
  if ($owner == 'services' && $api == 'services') {
    return array(
      'version' => 3,
      'file' => 'casa_services.module', // Optional parameter to indicate the file name to load.
      'path' => drupal_get_path('module', 'casa_services'), // If specifying the file key, path is required.
    );
  }
}



/**
 * Implements hook_default_services_endpoint().
 */
function casa_services_default_services_endpoint() {
  $endpoints = array();

  return $endpoints;
}

/**
 * Get the current user details.
 *
 * @return
 *   A user object.
 */
function _user_resource_current_user() {
  $uid = $GLOBALS['user']->uid;
  // dpm($uid, 'uid');

  module_load_include('inc', 'services', 'resources/user_resource');
  $user = _user_resource_retrieve($uid);

  return $user;
}



// /**
//  * Implements hook_rest_server_request_parsers_alter().
//  */
// function casa_services_rest_server_request_parsers_alter(&$parsers) {
//   dpm($parsers, '$parsers');
// }

// /**
//  * Implements hook_rest_server_request_parsed_alter().
//  */
// function casa_services_rest_server_request_parsed_alter(&$data, $controller) {
//   dpm($data, '$data');
//   dpm($controller, '$controller');
// }
